# Dockerfile_web_server

# Use the 'adoptopenjdk' base image with Java 17
FROM openjdk:17-jdk

# Set the working directory
WORKDIR /app

# Command to keep the container running
ENTRYPOINT ["tail", "-f", "/dev/null"]
