# ansible-playbook/web_server.yml

---
- hosts: localhost
  # connection: local  # Use local connection plugin
  gather_facts: false
  # become: yes  # Elevate privileges

  tasks:
    # - name: Deploy Petclinic App
    #   copy:
    #     src: /var/jenkins_home/workspace/petclinic-pipeline/target/spring-petclinic-3.1.0-SNAPSHOT.jar
    #     dest: /app/petclinic_app.jar
    #     mode: 0644

    - name: Use SSH port forwarding to copy JAR from Jenkins container to destination container
      command: scp -P 2222 /var/jenkins_home/workspace/petclinic-pipeline/target/spring-petclinic-3.1.0-SNAPSHOT.jar root@localhost:/app/petclinic_app.jar
      delegate_to: localhost  # Execute the command on the Jenkins container

    - name: Ensure destination container is running
      docker_container:
        name: yurenwan_assignment1docker-web_server-1  # name of the destination container
        image: yurenwan_assignment1docker-web_server:latest  # image name and tag of the destination container
        state: started

    - name: Start Petclinic Application
      command: "java -jar /app/petclinic_app.jar > /app/petclinic.log 2>&1 &"
      async: 0
      poll: 0
