# ansible-playbook/web_server.yml

---
- hosts: docker
  vars:
    ansible_connection: docker
  tasks:
    - name: Deploy Petclinic App
      copy:
        src: /var/jenkins_home/workspace/petclinic-pipeline/target/spring-petclinic-3.1.0-SNAPSHOT.jar
        dest: /app/petclinic_app.jar
        mode: 0644

    - name: Start Petclinic Application
      command: "java -jar /app/petclinic_app.jar > /app/petclinic.log 2>&1 &"
      async: 0
      poll: 0
