# ansible-playbook/web_server.yml

---
- hosts: localhost
  connection: local  # Use local connection plugin

  tasks:
    - name: Create /app directory
      become: yes  # Elevate privileges for this task
      file:
        path: /app
        state: directory
        mode: 0755

    - name: Deploy Petclinic App
      copy:
        src: /var/jenkins_home/workspace/petclinic-pipeline/target/spring-petclinic-3.1.0-SNAPSHOT.jar
        dest: /app/your_petclinic_app.jar
        mode: 0644

    - name: Start Petclinic Application
      command: "java -jar /app/your_petclinic_app.jar > /app/petclinic.log 2>&1 &"
      async: 0
      poll: 0
