# ansible-playbook/web_server.yml

---
- hosts: localhost
  connection: local  # Use local connection plugin

  tasks:
    - name: Deploy Petclinic App
      copy:
        src: /path/to/your_petclinic_app.jar
        dest: /app/your_petclinic_app.jar
        mode: 0644

    - name: Start Petclinic Application
      command: "java -jar /app/your_petclinic_app.jar > /app/petclinic.log 2>&1 &"
      async: 0
      poll: 0
